### ISSUE TITLE
unrecognized function: ieNotDefined

### ISSUE THREAD

**Issue by nicobast** [csb0/PCDM#1]
Tried to run the PCDM toolbox with the sample data and throws me an error:

Unrecognized function or variable 'ieNotDefined'.

`Error in fitK (line 31)
if ieNotDefined('samplingRate')

Error in fitModel (line 23)
[k, k_CI] = fitK(d.saccTimes, d.sampleRate, 1);
 `
When commenting out lines 31-38 in fitK.m, the sample data runs fine. Just want to make sure that I did not overlook something. Of note, my matlab skills are a little rusty

**Comment by csb0** [comment]
Hi Nico,

Thanks for pointing this out!

What you did is fine. ieNotDefined just defines default inputs to the function fitK, so in this case by default the function assumes an input data sampling rate of 500 Hz and outputs some diagnostic plots.

I've pushed a change that adds ieNotDefined.m to the utilities folder, so hopefully no one else should run into this issue. 

Please let me know if you run into any more issues.

Best,
Charlie

**Comment by nicobast** [comment]
Great, thanks for the quick fix. The model is exciting! Currently trying to apply your model to our oddball data. Will see how it works in these short per-trial durations with few saccades

**Comment by csb0** [comment]
Cool! Should you need any help fitting the model to your dataset, feel free to reach out. 

Charlie
