### ISSUE TITLE
set in.predictionWindow to correct value

### ISSUE THREAD

**Issue by nicobast** [csb0/PCDM#3]
Me again. The code now runs without errors. However, you have this comparison in the code:
`in.predictionWindow>maxTrialLength`

In the documentation, you indicate that predictionWindow should be a time window. However, maxTrialLength is a length in the number of trials. So, this comparison would not make that much sense, if you set predictionWindow to a scale of time. So, I just set predictionWindow to a number of samples that should be considered. Maybe, this could be updated in the documentation?

**Comment by csb0** [comment]
I'm pretty sure this is a bug, so thanks! I will fix this. 

Both variables should be in samples. What you did is fine.

**Comment by nicobast** [comment]
thanks and related to that:
`error('Prediction window must be longer than max trial length')`

I think, it should be: "Prediction window must be shorter than max trial length"

**Comment by csb0** [comment]
Fixed.
