### ISSUE TITLE
putativeIRFdur has no effect on IRF duration estimate

### ISSUE THREAD

**Issue by nicobast** [csb0/PCDM#5]
I noticed that in the fitParametricPuRFfromData.m you define:

`impulseTime = 4000; % 4 seconds. this is an assumption used throughout, based on observation that saccade-locked purf goes back to baseline after 4 sec
`
this option is hardcoded and thus does not consider the user defined in.putativeIRFdur from dataAnalysis. I guess, all estimate will be on a 4 second time window irrespective of the in.putativeIRFdur.

**Comment by csb0** [comment]
So this is a general guideline, based on our observations. This shouldn't be set shorter than 3 seconds, though.

**Comment by csb0** [comment]
I'm considering removing the option to set the putative IRF duration yourself. It should only be adjusted if the user does principled model comparisons with different IRF lengths, and then measures the generalization performance of the model, probably using our dataset.

**Comment by nicobast** [comment]
Great, thanks! will test your updates next week, as I am on conferences now.

**Comment by nicobast** [comment]
okay, will leave the putative IRF duration at 4s.
