### ISSUE TITLE
downsampling is mandatory and not optional

### ISSUE THREAD

**Issue by nicobast** [csb0/PCDM#7]
As we have just 300Hz data, I would like to avoid downsampling. However when setting:

`op.downsampleRate = 1`

the following error is given:

> Error using downsample
Expected PHASE to be a scalar with value <= 0.

> Error in downsample (line 51)
validateattributes(phase,{'numeric'},{'scalar','nonempty','integer','nonnegative','<=',N-1},'downsample','PHASE');

> Error in gainFinder (line 110)
predT2(kk,:) = downsample(predT,d.downsampleRate,1);

> Error in fitModel (line 41)
    [d, temp] = gainFinder(d,ii,op); % ii index is for runs

**Comment by csb0** [comment]
Fixed. Let me know if you still have issues with this.

**Comment by nicobast** [comment]
great, your fix has solved it
